### ISSUE TITLE
Error due to multiple Draft.js editors

### ISSUE THREAD

**Issue by pgandla** [samuelmeuli/mini-diary#44]
```
TypeError: Cannot read property 'getIn' of undefined
    at e.exports (file:///snap/mini-diary/4/resources/app.asar/bundle/renderer.js:21:230406)
    at e.exports (file:///snap/mini-diary/4/resources/app.asar/bundle/renderer.js:21:229945)
    at e.exports (file:///snap/mini-diary/4/resources/app.asar/bundle/renderer.js:21:228911)
    at e.exports (file:///snap/mini-diary/4/resources/app.asar/bundle/renderer.js:21:228269)
    at file:///snap/mini-diary/4/resources/app.asar/bundle/renderer.js:87:98276
    at Object.m (file:///snap/mini-diary/4/resources/app.asar/bundle/renderer.js:37:1024)
    at k (file:///snap/mini-diary/4/resources/app.asar/bundle/renderer.js:37:1167)
    at file:///snap/mini-diary/4/resources/app.asar/bundle/renderer.js:37:1313
    at S (file:///snap/mini-diary/4/resources/app.asar/bundle/renderer.js:37:1399)
    at T (file:///snap/mini-diary/4/resources/app.asar/bundle/renderer.js:37:1848)
```

---

Mini Diary 2.5.0
Electron 7.1.2
linux 5.3.0-24-generic
Locale: en-GB

**Comment by samuelmeuli** [comment]
@deepudoit Could you please provide more information? When does this error occur?

**Comment by samuelmeuli** [comment]
Seems to be a bug in `draft-js-plugins-editor` or Draft.js, and having multiple editors on the same page (in Mini Diary's case, that's the entry title and text editors). See https://github.com/draft-js-plugins/draft-js-plugins/issues/298.

I cannot reproduce this error, though. @deepudoit, please let me know if you manage to do so.

**Comment by samuelmeuli** [comment]
Closing due to inactivity. If someone can reproduce this, please let me know.
