### ISSUE TITLE
Crash when deleting lines

### ISSUE THREAD

**Issue by dmg59** [samuelmeuli/mini-diary#45]
```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ga (file:///Applications/Mini%20Diary.app/Contents/Resources/app.asar/bundle/renderer.js:37:77609)
    at Ia (file:///Applications/Mini%20Diary.app/Contents/Resources/app.asar/bundle/renderer.js:37:81585)
    at Wa (file:///Applications/Mini%20Diary.app/Contents/Resources/app.asar/bundle/renderer.js:37:84902)
    at file:///Applications/Mini%20Diary.app/Contents/Resources/app.asar/bundle/renderer.js:37:98278
    at Object.t.unstable_runWithPriority (file:///Applications/Mini%20Diary.app/Contents/Resources/app.asar/bundle/renderer.js:45:3218)
    at Es (file:///Applications/Mini%20Diary.app/Contents/Resources/app.asar/bundle/renderer.js:37:98213)
    at Ts (file:///Applications/Mini%20Diary.app/Contents/Resources/app.asar/bundle/renderer.js:37:97989)
    at Ds (file:///Applications/Mini%20Diary.app/Contents/Resources/app.asar/bundle/renderer.js:37:97334)
    at Ps (file:///Applications/Mini%20Diary.app/Contents/Resources/app.asar/bundle/renderer.js:37:98709)
    at Dn (file:///Applications/Mini%20Diary.app/Contents/Resources/app.asar/bundle/renderer.js:37:30567)
```

---

Mini Diary 2.4.1
Electron 5.0.8
darwin 19.0.0
Locale: en-GB

**Comment by samuelmeuli** [comment]
@dmg59  Could you please provide more information? When does this error occur?

**Comment by dmg59** [comment]
I wanted to delete a few lines and it just crashed 

Diana Gariany
dmgariany@icloud.com
Skype: dghariany59
Twitter:@DGhariany
Facebook:diana.ghariany

**Comment by samuelmeuli** [comment]
This seems to be related to Draft.js; it might be this issue: https://github.com/facebook/draft-js/issues/1320

@dmg59 Have you been able to reproduce the error?

**Comment by samuelmeuli** [comment]
I've applied the workaround mentioned in https://github.com/facebook/draft-js/issues/1320. Please let me know if this issue still occurs after the next Mini Diary release :)

**Comment by dmg59** [comment]
Ok

Diana Gariany
dmgariany@icloud.com
Skype: dghariany59
Twitter:@DGhariany
Facebook:diana.ghariany

**Comment by samuelmeuli** [comment]
This workaround unfortunately introduced an auto-scrolling bug (#47). I've reverted it as I consider the other problem more severe, and this issue should be fixed in Draft.js instead.
