### ISSUE TITLE
Auto-update fails with error

### ISSUE THREAD

**Issue by alexriabtsev** [samuelmeuli/mini-diary#49]
**Stack trace:**

```
Error: net::ERR_CONNECTION_RESET
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2533:21)
    at SimpleURLLoaderWrapper.emit (events.js:203:13)
```

---

**Environment:**

```
Mini Diary 2.5.1
Electron 7.1.3
darwin 19.2.0
Locale: en-GB
```

---

**Error description:**

**Comment by samuelmeuli** [comment]
Duplicate of #48
