### ISSUE TITLE
Auto-update fails with error

### ISSUE THREAD

**Issue by anunayajoshi** [samuelmeuli/mini-diary#51]
**Stack trace:**

```
Error: Redirect was cancelled
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2558:23)
    at SimpleURLLoaderWrapper.emit (events.js:203:13)
```

---

**Environment:**

```
Mini Diary 2.5.1
Electron 7.1.3
win32 10.0.18362
Locale: en-US
```

---

**Error description:**

**Comment by samuelmeuli** [comment]
Duplicate of #48
