### ISSUE TITLE
Auto-update fails with error

### ISSUE THREAD

**Issue by gardelin** [samuelmeuli/mini-diary#55]
**Stack trace:**

```
Unhandled Promise Rejection Error
Error: Redirect was cancelled
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2558:23)
    at SimpleURLLoaderWrapper.emit (events.js:203:13)
```

---

**Environment:**

```
Mini Diary 2.5.1
Electron 7.1.3
darwin 19.0.0
Locale: en-GB
MacOs 10.15
```

---

**Error description:**

Error occurs when starting application. The application can still be used normally.

**Comment by samuelmeuli** [comment]
Duplicate of #48
